services:

  # Database Service
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: mnemosyne
      POSTGRES_PASSWORD: moneta
      POSTGRES_DB: mnemosyne
    volumes:
      - mnemosyne_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mnemosyne -d mnemosyne"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mnemosyne_data:
    driver: local
